### ISSUE TITLE
Tests don't pass with freshly cloned repository

### ISSUE THREAD

**Issue by cmd-johnson** [mulesoft-labs/osprey-method-handler#23]
Currently, cloning this repository, running `npm install && npm test` produces errors. Looks like they are related to `node-raml-validate` changing the default RAML-version to 0.8 in mulesoft-labs/node-raml-validate@b9ce7cf47437b92321f12de20fd1e87fdbdac2a5. Manually passing `{ RAMLVersion: 'RAML10' }` to the `validate` calls in the failing test cases makes the tests go green again. (PR pending)

**Comment by jstoiko** [comment]
good catch. thanks for this! I will merge and publish a new version when the other packages are ready for an update.
